name: Run Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"  # or your preferred version

      - name: Install uv and deps
        run: |
          pip install uv
          uv sync --dev

      - name: Run pytest
        run: uv run pytest
